### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [TauChan/alpha#1]
on your code here:

``` js
var sql = (file) => pgp.QueryFile(file,{debug: true, minify: false})
```

Option `minify` is false by default, but it is the one recommended for use, as it shrinks the SQL a lot. That, plus option `compress`.

And while it is stated in multiple places that one instance of `QueryFile` should be created per file, you are creating it dynamically for every request. This pretty much devalues class `QueryFile`, and its option `debug` would do nothing, as you keep recreating the class.

See [the API](http://vitaly-t.github.io/pg-promise/QueryFile.html) for more details.

**Comment by techanon** [comment]
The sql function is only present in the installation script. It is unassociated with connections of users since install/app.js is only for the initializing of the data for the product instance and ran by someone with terminal access. All connection based SQL will be cached in the GLOBAL.sql object upon app startup as seen here: https://github.com/TauChan/alpha/blob/techborn-dev/app.js#L21.

Also if you examine that install/app.js script closer, you will see that each file is only loaded once during the lifetime of the script.
